# Jekyll Defaults
title: Light Keima
description: A penguin loves computers.
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://lightkeima.github.io/"
github: http://github.com/lightkeima
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
